base_model: 'swinir'
img_size: 416
window_size: 8
embed_dim: 180
upsampler: "pixelshuffle"
in_channels: 1
num_heads:
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
depths:
  - 6
  - 6
  - 6
  - 6
  - 6
  - 6
learning_rate: 0.0001
b1: 0.9
b2: 0.999
# Loss function relative percentages
loss:
  l1: 1.0
  poisson: 0.0
  psnr: 0.0
  ssim: 0.0
  ms_ssim: 0.0
  vgg:
    p: 0.0
    vgg_model: vgg19
    batch_norm: False
    layers: 8
