program: train.py
method: random
name: esr_gen_model_params_extended_poisson
description: "Testing the influence of the model params: batch_size, learning_rate, num_filters, residual_blocks"
metric:
  name: val/loss
  goal: minimize
parameters:
  batch_size:
    values: [2, 4]
  learning_rate:
    values: [0.0005, 0.0001, 0.00005]
  filters:
    values: [16, 32, 64]
  residual_blocks:
    values: [4, 8, 16]