[trainer]
accelerator = "auto"
strategy = "auto"
checkpoint_path = ""
devices = "auto"
epochs = 50
# log_images_every_n_epochs is currently ignored. WIP
log_images_every_n_epochs = 0
checkpoint_root = ""

[dataset]
agn = true
bkg = true
batch_size = 1
debug = false
comb_hr = false
directory = ""
version = "v2"
name = "sim_dataset"
scaling = "sqrt"
type = "sim"

# Currently ignored. WIP
#[dataset.display]
#sim_display_name = "xmm_sim_display_selection"
#real_display_name = "xmm_split_display_selection"
#exposures = [20]

[dataset.lq]
det_mask = ""
exp = 20
clamp_max = 0.0022336 #TODO: aggresive max, 200 times background, this is +-111 counts on 50ks
res = 416

[dataset.hq]
exp = 100
det_mask = ""
clamp_max = 0.0005584 #TODO: aggresive max, 200 times background, this is +-11 counts on 50ks
res = 832

[model]
name = "esr_gen"
memory_efficient = false
