wandb:
  api_key:
  project:
  online: False
  log_model: True
  run:
    id:

trainer:
  accelerator: auto
  strategy: auto
  checkpoint_path:
  devices: auto
  epochs: 50
  log_images_every_n_epochs: 5
  checkpoint_dir:

dataset:
  batch_size: 1
  check_files: False
  # Options: 'center', 'random', 'boresight'
  crop_mode: center
  det_mask: True
  debug: False
  dir: /data/projects/xmm-epicpn-simulator/data/xmm_sim_dataset
  display:
    sim_display_name: xmm_sim_display_selection
    real_display_name: xmm_split_display_selection
    exposure:
      - 20
  lr:
    agn: 1
    background: 1
    exps:
      - 20
    max: 0.0022336 #TODO: aggresive max, 200 times background, this is +-111 counts on 50ks
    res: 416
  hr:
    agn: True
    background: False
    exp: 100
    max: 0.0005584 #TODO: aggresive max, 200 times background, this is +-11 counts on 50ks
    res: 832
  # The mode, img or agn. If agn the model samples from agn as if it is an image.
  mode: img
  name: scaled
  # Options: None and 'linear', 'sqrt', 'asinh', 'log'
  scaling: sqrt
  # Options: real, sim
  type: sim

model:
  name: esr_gen
  memory_efficient: False
