[wandb]
api_key = ""
project = ""
online = true
log_model = true
run_id = ""

[trainer]
accelerator = "auto"
strategy = "auto"
checkpoint_path = ""
devices = "auto"
epochs = 50
log_images_every_n_epochs = 0
checkpoint_root = ""

[dataset]
agn = 1
batch_size = 1
check_files = false
crop_mode = "center"
debug = false
directory = ""
comb_hr = false
# The mode, img or agn. If agn the model samples from agn as if it is an image.
mode = "img"
name = "sim_dataset"
scaling = "sqrt"
type = "sim"

#[dataset.display]
#sim_display_name = "xmm_sim_display_selection"
#real_display_name = "xmm_split_display_selection"
#exposures = [20]

[dataset.lr]
bkg = 1
det_mask = ""
exps = [20]
clamp_max = 0.0022336 #TODO: aggresive max, 200 times background, this is +-111 counts on 50ks
res = 416

[dataset.hr]
agn = true
exp = 100
det_mask = ""
clamp_max = 0.0005584 #TODO: aggresive max, 200 times background, this is +-11 counts on 50ks
res = 832

[model]
name = "esr_gen"
memory_efficient = false
