wandb:
  api_key:
  project:
  online: True
  log_model: True
  run:
    id:

trainer:
  accelerator: auto
  strategy: auto
  checkpoint_path:
  devices: auto
  epochs: 300
  log_images_every_n_epochs: 5

dataset:
  batch_size: 1
  check_files: False
  # Options: 'center', 'random', 'boresight'
  crop_mode: center
  # set whether or not to clamp the input data (added by Yvonne) 
  clamp: False
  det_mask: True
  debug: False
  dir: "/xmm-super/final_data/sim/"
  # dir: /home/xmmsas/mywork/xmm-superres-denoise/data/example_data/real
  display:
    sim_display_name: xmm_sim_display_selection
    real_display_name: xmm_split_display_selection
    exposure:
      - 20
  lr:
    agn: 1
    background: 1
    exps:
      - 20
    max: 0.0022336 #TODO: aggresive max, 200 times background, this is +-111 counts on 50ks
    res: 416
  hr:
    agn: True
    background: False
    exp: 50
    max: 0.0005584 #TODO: aggresive max, 200 times background, this is +-11 counts on 50ks
    res: 832
  # The mode, img or agn. If agn the model samples from agn as if it is an image.
  mode: img
  name: xmm_sim_dataset
  # name: ""
  # Options: None and 'linear', 'sqrt', 'asinh', 'log', 'hist_eq'
  scaling: sqrt
  # parameters for normalization (added by Yvonne)
  asinh: 
    a: 0.02
  log:
    a: 1000 
  # Options: real, sim
  type: sim

model:
  name: esr_gen
  memory_efficient: False