model_name: esr_gen_medium  # Options: 'esr_gen', 'esr_gan', 'sr_cnn',  'sr_flow'
dataset_name: xmm_sim_bc
datasets_dir: /home/ssweere/data # "/home/sam/Documents/ESA/data/sim"

end_to_end_test: False
fast_dev_run: False
debug: False

runs_dir: /home/ssweere/data/runs # '/home/sam/Documents/ESA/data/runs', "/home/ssweere/remote_home/data/runs" ## The run specific folder will be created automatically
epochs: 1000
gpus: [2] #cpu: null, gpu: [0] (give the gpu number)
batch_size: 4
log_every_n_steps: 100
log_images_every_n_epoch: 5

resume_from_checkpoint: False  # TODO: this does not yet work with wandb and other settings
resume_model_checkpoint_path: '/home/sam/Documents/ESA/data/runs/test/3r51n1ap/checkpoints/test-epoch=00002-val_loss=0.00.ckpt'