wandb:
  api_key: 
  project: xmmsr_test
  online: True
  log_model: True
  run:
    id:

trainer:
  accelerator: auto
  strategy: auto
  checkpoint_path:
  devices: 0, 2
  epochs: 50
  log_images_every_n_epochs: 5

dataset:
  batch_size: 2
  check_files: False
  # Options: 'center', 'random', 'boresight'
  crop_mode: center
  # set whether or not to clamp the input data
  clamp: False
  sigma_clamp: False
  quantile_clamp: False  #0.9999
  normalize: True
  constant_img_combs: True # Set to true to ensure that the same AGN and background components are used per idx every time
  det_mask: True
  debug: True
  dir: "/xmm-super/final_data/sim/"
  # dir: "/xmm-super/final_data/real/"
  # deblend_agn_dir: "blended_agn"
  deblend_agn_dir: False
  display:
    sim_display_name: xmm_sim_display_selection
    # sim_display_name: xmm_sim_comp_img
    # real_display_name: False
    real_display_name: xmm_split_display_selection
    comps: False # If True the display images are also composed of img, agn and background
    exposure:
      - 20
  lr:
    agn: True
    background: 1
    exps:
      - 20
    max: 0.0022336 #TODO: aggresive max, 200 times background, this is +-111 counts on 50ks
    res: 256 #416
  hr:
    agn: True
    background: False
    exp: 100
    max: 0.0005584 #TODO: aggresive max, 200 times background, this is +-11 counts on 50ks
    res: 512 # 832
  # The mode, img or agn. If agn the model samples from agn as if it is an image.
  mode: img
  name: xmm_sim_dataset
  # name: xmm_real_split_dataset
  # name: ""
  # Options: None and 'linear', 'sqrt', 'asinh', 'log', 'hist_eq'
  scaling: sqrt
  # parameters for normalization (added by Yvonne)
  asinh: 
    a: 0.02
  log:
    a: 1000
  hist_eq:
    tileGridSize: 4
    clipLimit: 2.0
  # Only use input above ('above') or below ('all'). Use 'all' to use the entire dataset
  divide_dataset: 'below'  # options are: 'above', 'below', 'all'
  
  # Options: real, sim
  type: sim

model:
  name: esr_gen
  memory_efficient: True
  normalization_layer: False

