base_model: 'rrdb_denoise'
in_channels: 2
out_channels: 1
filters: 16
residual_blocks: 3
learning_rate: 0.0001
b1: 0.9
b2: 0.999
# Loss function relative percentages
loss_l1: 0.0
loss_poisson: 1.0
loss_psnr: 0.0
loss_ssim: 0.0
loss_ms_ssim: 0.0