base_model: sr_flow

# Based on SRFlow_DF2K_4X.yml


#### general settings
#name: train
#use_tb_logger: true
#model: SRFlow
#distortion: sr
scale: 2
#gpu_ids: [ 0 ]

#inference_heat: 0.5 # Added by me

#### network structures
network_G:
#  which_model_G: SRFlowNet


  in_nc: 1
  out_nc: 1
  nf: 64 # 64
  nb: 23 # 23
  upscale: 2
#  train_RRDB: false
#  train_RRDB_delay: 0.5
#  train_RRDB_delay_epoch: 20 #TODO: this number is random picked change it

  flow:
    K: 8 # 16
    L: 2 # number of levels, put it to 3 for scale 4
    noInitialInj: true
    coupling: CondAffineSeparatedAndCond
    additionalFlowNoAffine: 2
    split:
      enable: true
      correct_splits: False # Added by me
      logs_eps: 0 # Added by me
      consume_ratio: 0.5 # Added by me
      conditional: False # Added by me
      cond_channels: False # Added by me
      type: Split2d # Added by me



    fea_up0: true
    stackRRDB:
      blocks: [ 1, 8, 15, 22 ]
      concat: true

    hidden_channels: 64 # 64 # Added by me
    augmentation: # Added by me
      noiseQuant: True # Added by me

    condAff: False # Added by me

    levelConditional: # Added by me
      conditional: False # Added by me


#### training settings: learning rate scheme, loss
train:
  manual_seed: 10
  lr_G: !!float 2.5e-4
  weight_decay_G: 0
  beta1: 0.9
  beta2: 0.99
#  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps_rel: [ 0.5, 0.75, 0.9, 0.95 ]
  lr_gamma: 0.5

#  niter: 200000 #TODO: this needs to be stated somewhere else
#  val_freq: 40000 #TODO: this needs to be stated somewhere else
  weight_fl: 1 #Added by me
  weight_l1: 0 #Added by me


#### validation settings
val:
  heats: [ 0.0, 0.25, 0.5, 0.75, 1.0 ]
#  n_sample: 3

#### datasets
#datasets:
# train:
#    name: CelebA_160_tr
#    mode: LRHR_PKL
#    dataroot_GT: ../datasets/DF2K-tr.pklv4
#    dataroot_LQ: ../datasets/DF2K-tr_X4.pklv4
    # TODO: this is not used when add_gt_noise is False, which it is
    # quant: 100 #TODO: have a look how to handle this

#    use_shuffle: true
#    n_workers: 3  # per GPU
#    batch_size: 12
#    GT_size: 160
#    use_flip: true
#    color: RGB
#  val:
#    name: CelebA_160_va
#    mode: LRHR_PKL
#    dataroot_GT: ../datasets/DIV2K-va.pklv4
#    dataroot_LQ: ../datasets/DIV2K-va_X4.pklv4
#    quant: 32
#    n_max: 20