program: train.py
method: random
metric:
  name: val/l1
  goal: minimize
parameters:
  batch_size:
    values: [1, 2, 4, 8]
  learning_rate:
    distribution: uniform
    min: 0.00001
    max: 0.001
  filters:
    values: [4, 8, 16, 32]
  residual_blocks:
    distribution: int_uniform
    min: 1
    max: 9