datasets_dir: "../data/example_data/sim"
dataset_name: "combined"
dataset_type: "sim"
include_hr: True # Includes the high resolution target file (only set this to True if you have high resolution reference files)
lr_res: 416 # Must be multiples of 32
hr_res: 832 # This implies the resolution increase
dataset_lr_res: 416 # The dataset lr resolution, all the images will be padded/cropped to this resolution
lr_exp: 20 # Exposure of the low resolution images, in ks
hr_exp: 100 # Exposure of the high resolution images, in ks
mode: img # The mode, img or agn. If agn the model samples from agn as if it is an image
lr_agn: True # Include agns in the low resolution images
hr_agn: True # Include agns in the high resolution images
lr_background: True # Include background for lr
hr_background: False # Include background for hr
det_mask: True # Apply the detector mask
exp_channel: True #Add exposure channel
data_scaling: sqrt # Other options None and 'linear', 'sqrt', 'asinh', 'log'
crop_mode: center # Options: 'center', 'random', 'boresight'
lr_max: 0.0022336 #200 times background, this is +-111 counts on 50ks
hr_max: 0.0005584 #200 times background, this is +-11 counts on 50ks


